name: ${project.name}
main: net.cyberflame.antienemysilk.AntiEnemySilkPlugin
depend: [Factions]
version: ${project.version}
permissions:
  aes.bypassnearbyenemycheck:
   description: Bypasses spawner enemy check
   default: op
